"""Artifact discovery helpers for APK/AAB builder tooling."""
from __future__ import annotations

import hashlib
from pathlib import Path


_ARTIFACT_PATTERNS = (
    "apk_builds/*.apk",
    "apk_builds/*.aab",
    "build/app/outputs/flutter-apk/*.apk",
    "build/app/outputs/apk/release/*.apk",
    "build/app/outputs/bundle/release/*.aab",
)


def sha256_file(file_path: Path) -> str:
    """Return SHA-256 hex digest for a file without loading it all into memory."""
    digest = hashlib.sha256()
    with Path(file_path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def find_latest_artifact(project_root: Path, flutter_project: Path) -> Path | None:
    """Find the newest APK/AAB generated by the builder or Flutter.

    The function only discovers artifacts already present on disk; it never builds
    or copies artifacts by itself.
    """
    roots = [Path(project_root), Path(flutter_project)]
    candidates: list[Path] = []
    for root in roots:
        for pattern in _ARTIFACT_PATTERNS:
            candidates.extend(path for path in root.glob(pattern) if path.is_file())
    if not candidates:
        return None
    return max(candidates, key=lambda path: path.stat().st_mtime)
