// Template configuration for source control.
// APK Builder GUI overwrites this file locally with a real BUILD-* token.
// Do not commit generated build tokens from local release builds.

class AppConfig {
  static const String serverUrl = "https://man1rokanhulu.cloud/";
  static const String appName = "SIAB1 — Sistem Informasi Asesmen Berintegritas";
  static const bool forceHttps = true;
  static const bool allowCleartextTraffic = false;
  static const String buildMode = "universal_apk";
  static const String resilienceProfile = "ux_offline_first";

  // Placeholder only. Release APK builds must be generated by APK Builder GUI.
  static const String buildToken = "BUILD-TEMPLATE-LOCAL";
  static const int buildTimestamp = 0;

  // UX-first offline runtime tuning
  static const bool enableOfflineFirstRuntime = true;
  static const bool showConnectionBadge = true;
  static const bool enableAdaptiveViolationDetection = true;
  static const bool enableDiagnosticsQuickExport = true;
  static const int reconnectProbeIntervalSeconds = 10;
  static const int emergencyExitMinOutageMinutes = 3;
  static const int emergencyExitMinFailedProbes = 6;
  static const double riskAutoSubmitThreshold = 8.5;
  static const int answerJournalSyncIntervalSeconds = 8;
  static const int answerJournalBatchSize = 80;
  static const int timerGuardMaxDriftSeconds = 12;

  // Security Settings
  static const bool enableKiosk = true;
  static const bool blockScreenshot = true;
  static const bool detectRoot = true;
  static const bool blockTaskSwitch = true;
}
